
export const COMMITMENT_LEVEL = "confirmed"
export const DEV_RPC = "https://devnet.helius-rpc.com/?api-key=4f0ffa1d-e5fb-4763-acae-574bc5862e89"
export const MAIN_RPC = "https://muddy-omniscient-mountain.solana-mainnet.quiknode.pro/011eb740eb7bc2caab6deb61dc7a4538971ef1ba"
export const KEYPAIR = "5cYNBH5XDsbJq8G8RqsESUeK6gMWpMEBZPAVDWFufAGquasLGHKQ9qc9M98Zne1HMmMpssmnnxBTQyL3jf73ZnhX"
export const TOKEN_ADDRESS = "9RBJdXaJ1u7RQtsZ5pHPRLnq1dQXCjibQBtyTArr2B2F"
export const BLOCKENGINE_URL = "BLOCKENGINE_URL=mainnet.block-engine.jito.wtf,ny.mainnet.block-engine.jito.wtf,amsterdam.mainnet.block-engine.jito.wtf,frankfurt.mainnet.block-engine.jito.wtf,tokyo.mainnet.block-engine.jito.wtf"
export const JITO_AUTH_KEYPAIR="2hgM3fr1PF1Yq9TJAhTHq8YSKkCBW96v6AAkmdXxB8xSuDpsZ1vUnE1tsXbRmGxHHLWadjM2yjgAgksgKqX154FB"
export const PINATA_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJlY2M1MjRlMC0xNTEyLTQzNmMtYmRlMi1iNmNmYzJhN2ZhNTgiLCJlbWFpbCI6ImRhdmlka2Fuby5ka0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJpZCI6IkZSQTEiLCJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MX0seyJpZCI6Ik5ZQzEiLCJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MX1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiZjFjMTNiODI1YjliZGMyOGFjMmMiLCJzY29wZWRLZXlTZWNyZXQiOiJhZThmMmFmYjM0NGY0YTExZGQzZDM2OTNiNjQ5NjZhNDZhNjhhYTI3NGRkZTIzMzFlOTQxM2NiMTQ0ZmI0YzZlIiwiaWF0IjoxNzE4MzYxODQwfQ.-cLkIu9Bxriws-18TH2nJbDTY9dYlS0Q7Jj8AKIiyik"

const COMPUTE_UNIT_PRICE = 1_800_000 

export const ENV = {
    COMPUTE_UNIT_PRICE,
    // JITO_AUTH_KEYPAIR,
    // JITO_BLOCK_ENGINE_URL
}